### PR TITLE
Fix issue #196 - Add email signup for DE

### LINKED ISSUE #196: Add an email sign-up form for DE thank you page

### PR DESCRIPTION
**Pull request by alicoding**
closes #196

### CODE REVIEW

**Comment by alicoding** [comment]
@ScottDowne R?

File: pages/thank-you.jsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ var ThankYou = React.createClass({
                 </h2>
               </div>
             </div>
-            {this.props.params && this.props.params.locale === 'en-US' ? <Signup/> : <Social/> }
+            {this.props.params && ['de', 'en-US'].indexOf(this.props.params.locale) !== -1 ? <Signup language={this.props.params.locale }/> : <Social/> }
```
Comment (ScottDowne) [inline pages/thank-you.jsx]: This might get interesting... but fine for now.
