### PR TITLE
Capture and record recurring txn failures properly

### LINKED ISSUE #1880: SFDC Upsert failing for failed recurring transactions
For recurring donations that fail, the upsert is failing in SFDC b/c it's missing the Close Date and StageName values. What is happening is that the transaction ID is not found in SFDC, so a new record is attempting to be created, but the fields needing to create a new record are not included in the data coming in from Stripe.

(1) We need to make sure that only specific failures are coming through Stripe 
(2) The same fields used to create a new donation Oppty record in SFDC should be passed over for these failures

### PR DESCRIPTION
**Pull request by cadecairos**
Fixes #1880

### CODE REVIEW

File: server/routes/webhooks/stripe-charge-failed.js [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+  if (!event) {
+    return reply(boom.forbidden(forbiddenError));
+  }
+
+  // Only process charge.failed webhook events
+  if (event.type !== event_type) {
+    return reply(incorrectEventError);
+  }
+
+  let {charge} = event.data.object;
```
Comment (gideonthomas) [inline server/routes/webhooks/stripe-charge-failed.js]: why do we destructure `event.data.object`? Is there a `charge` property on `event.data.object`?

File: server/routes/webhooks/stripe-charge-failed.js [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+
+  // If the charge has no invoice ID, this is not a recurring charge
+  if (!charge.invoice) {
+    return reply(notRecurringCharge);
+  }
+
+  // Expand the invoice object on the charge
+  stripe.retrieveCharge(charge.id, (fetchChargeError, charge) => {
+    if (fetchChargeError) {
+      return reply(boom.badImplementation(`${expandChargeError}: ${fetchChargeError}`));
```
Comment (gideonthomas) [inline server/routes/webhooks/stripe-charge-failed.js]: one thing to note here is that if `fetchChargeError` is an object and you use string interpolation, it will show up as `[object Object]`

File: server/routes/webhooks/stripe-charge-failed.js [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+    if (!charge.invoice || !charge.invoice.subscription) {
+      return reply(notPartOfSubscription);
+    }
+
+    let {customer, subscription} = charge.invoice;
+
+    // Expand the subscription object
+    stripe.retrieveSubscription(customer, subscription, (retrieveSubscriptionError, subscription) => {
+      if (retrieveSubscriptionError) {
+        return reply(boom.badImplementation(`${retrieveSubscriptionErrorMsg}: ${retrieveSubscriptionError}`));
```
Comment (gideonthomas) [inline server/routes/webhooks/stripe-charge-failed.js]: same note here

File: server/routes/webhooks/stripe-charge-failed.js [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+      }
+
+      // Capture the variables we need to pass to the CRM
+      // Since this charge failed, we need to pass enough information
+      // for the CRM to create a new Opportunity record, and mark it
+      // immediately as 'Lost'
+      let {
+        currency,
+        created,
+        id: transaction_id,
```
Comment (gideonthomas) [inline server/routes/webhooks/stripe-charge-failed.js]: why destructure into `id` instead of leaving it as `transaction_id`? It doesn't seem like you use `id` anywhere but you redeclare it below and reassign it to `subscription_id`

File: server/routes/webhooks/stripe-charge-failed.js (hunk 1 above)
Comment (cadecairos) [reply server/routes/webhooks/stripe-charge-failed.js]: Good catch

File: server/routes/webhooks/stripe-charge-failed.js (hunk 2 above)
Comment (cadecairos) [reply server/routes/webhooks/stripe-charge-failed.js]: I can confirm this in the Stripe code, but I'm almost certain this will be an `Error`, and will have a useful toString implemented for outputting

File: server/routes/webhooks/stripe-charge-failed.js (hunk 4 above)
Comment (cadecairos) [reply server/routes/webhooks/stripe-charge-failed.js]: You've got your understanding of how this destructuring assignment works:

This line of code will look for `id` on the right operand (`charge`), and assign it's value to `transaction_id`. This is understandably confusing, especially if you try to liken this syntax to that of Object literals.

Here's a sample I ran in my browse console to illustrate:

Comment (gideonthomas) [reply server/routes/webhooks/stripe-charge-failed.js]: heh, yep, you're right, I totally read the docs wrong

**Comment by cadecairos** [comment]
@gideonthomas changes made to that destructuring assignment.
