### PR TITLE
Fix issue #1101 - zeroDecimal of undefined

### LINKED ISSUE #1101: Uncaught error: Cannot read property 'zeroDecimal' of undefined
```
 » 13 Dec 2015 16:55:59.759 2015-12-13 21:55:59.451045+00:00 app web.1 - - message="Uncaught error: Cannot read property 'zeroDecimal' of undefined" stack="TypeError: Uncaught error: Cannot read property 'zeroDecimal' of undefined at Object.amountModifier.modify (/app/scripts/amount-modifier.js:20:31) at Object.amountModifier.paypal (/app/scripts/amount-modifier.js:36:17) at routes.paypal (/app/routes/index.js:165:33) at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/app/node_modules/hapi/lib/handler.js:96:36) at /app/node_modules/hapi/lib/handler.js:30:23 at internals.Protect.run.finish [as run] (/app/node_modules/hapi/lib/protect.js:64:5) at exports.execute.finalize (/app/node_modules/hapi/lib/handler.js:24:22) at each (/app/node_modules/hapi/lib/request.js:378:16) at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13) at done (/app/node_modules/hapi/node_modules/items/lib/index.js:28:25) at request._protect.run (/app/node_modules/hapi/lib/validation.js:59:20) at internals.Any.applyFunctionToChildren.internals.Any._validateWithOptions (/app/node_modules/hapi/node_modules/joi/lib/any.js:657:16) at root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:102:23) at Object.internals.input.postValidate [as input] (/app/node_modules/hapi/lib/validation.js:131:20) at exports.payload (/app/node_modules/hapi/lib/validation.js:29:22) at each (/app/node_modules/hapi/lib/request.js:378:16)" tags=error timestring=2015-12-13T21:55:59.443Z Exception Context 
```

There are 6 of them in logentries.

### PR DESCRIPTION
**Pull request by alicoding**
closes #1101

### CODE REVIEW

**Comment by alicoding** [comment]
@jbuck or @ScottDowne or @cadecairos R?

File: lib/currency-for.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+var currencies = require('../data/currencies.js');
+module.exports = {
+  stripe: Object.keys(currencies),
+  paypal: Object.keys(currencies).filter(function(i) {
+    if (!currencies[i].hasOwnProperty('disabled')) {
```
Comment (jbuck) [inline lib/currency-for.js]: Could this be simplified to `return !currencies[i].hasOwnProperty('disabled')` ?

Comment (jbuck) [inline lib/currency-for.js]: Also, I think we should check this for `currencies[i].disabled !== 'paypal'`

Comment (jbuck) [inline lib/currency-for.js]: Maybe add the same check for the Stripe list as well?

Comment (alicoding) [inline lib/currency-for.js]: Stripe basically doesn't have that property at all and I believe we want all currencies in the list, so not sure if we need this now.

File: server.js [hunk 2]
```diff
@@ -94,7 +95,7 @@ module.exports = function() {
         },
         validate: {
           payload: {
-            currency: Joi.string().min(3).max(3).required(),
+            currency: Joi.any().valid(currencyFor.stripe),
```
Comment (jbuck) [inline server.js]: Do you need to add `.string()` or `.required()` on each of these lines?

Comment (jbuck) [inline server.js]: Wait, nevermind about `.string()`

Comment (alicoding) [inline server.js]: Not required to do that anymore since if the value doesn't match any of the values in the array then it will fail.

**Comment by jbuck** [comment]
@alicoding this looks great, but I think we should add some http tests here to ensure things are working as expected

File: server.js (hunk 2 above)
Comment (ScottDowne) [inline server.js]: Did you try it without required?

I remember some weirdness with min(3).max(3) would pass as undefined if I didn't say required.

**Comment by jbuck** [comment]
@alicoding r+ when this goes green

File: server.js (hunk 2 above)
Comment (jbuck) [inline server.js]: I did a test and got the following response:

```
{ statusCode: 400,
  error: 'Bad Request',
  message: 'child "currency" fails because ["currency" is required]',
  validation: { source: 'payload', keys: [ 'currency' ] } }
```
